// Generated by https://quicktype.io

export interface JSONSample {
    technologies: Technology[];
    courses:      Course[];
}

export interface Course {
    _id:  string;
    code: string;
    name: string;
}

export interface Technology {
    _id:         string;
    name:        string;
    description: string;
    difficulty:  number;
    courses:     TechnologyCourse[];
}

export interface TechnologyCourse {
    code: string;
    name: string;
}

// added course/tech class for adding new course/tech

export class Course {
    code: string;
    name: string;
}



export class Technology {
    _id:         string;
    name:        string;
    description: string;
    difficulty:  number;
    courses:     TechnologyCourse[];
}